In [1]:
from parascore import ParaScorer
import torch

C:\Users\benjc\miniconda3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
paraScorer = ParaScorer(lang="en", model_type="Qwen/Qwen3-Embedding-0.6B", num_layers=28)

C:\Users\benjc\miniconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\benjc\.cache\huggingface\hub\models--Qwen--Qwen3-Embedding-0.6B. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [3]:
from parascore.utils import diverse

In [4]:
ref = ["Lightning stitched silver veins through the bruise-purple sky while midnight rain drummed forgotten secrets against the attic window.",
       "Lightning stitched silver veins through the bruise-purple sky while midnight rain drummed forgotten secrets against the attic window."]
cands = ["Lightning stitched silver veins through the bruise-purple sky while midnight rain drummed forgotten secrets against the attic window.",
        "Homer Simpson is my father"]

In [5]:
ref_ = ["Lightning stitched silver veins through the bruise-purple sky while midnight rain drummed forgotten secrets against the attic window."]
cands_ = ["Lightning stitched silver veins through the bruise-purple sky while midnight rain drummed forgotten secrets against the attic window."]

In [6]:
diversity = diverse(cands, ref)
diversity

[-1.0, 0.35]

In [7]:
paraScorer.score(cands, ref, verbose=False, batch_size=64, return_hash=False)

(tensor([1.0000, 0.4531]), tensor([1.0000, 0.3174]), tensor([1.0000, 0.3733]))

In [8]:
similarity = paraScorer.score(cands, ref, verbose=False, batch_size=64, return_hash=False)

In [9]:
similarity

(tensor([1.0000, 0.4531]), tensor([1.0000, 0.3174]), tensor([1.0000, 0.3733]))

In [14]:
similarity[2].tolist()

[1.0, 0.3733022212982178]

In [22]:
paraScorer.free_score(cands, ref, verbose=False, batch_size=64, return_hash=False)

[tensor([0.9500, 0.4031]), tensor([1.0175, 0.3349])]

In [23]:
P, R, F1 = paraScorer.free_score(cands, ref, verbose=False, batch_size=64, return_hash=False)
F1

ValueError: not enough values to unpack (expected 3, got 2)

In [24]:
P, R, F1 = [x + 0.05*y for (x,y) in zip(similarity, diversity)]
P, R, F1

ValueError: not enough values to unpack (expected 3, got 2)

In [25]:
F1

tensor([0.9500])

In [11]:
alpha = 0.05                                 # keep the paper’s default
div  = torch.tensor(diversity, device=similarity[0].device)
print(div)
P, R, F1 = [sim + alpha * div for sim in similarity]
P, R, F1

tensor([-1.0000,  0.3500])


(tensor([0.9500, 0.4706]), tensor([0.9500, 0.3349]), tensor([0.9500, 0.3908]))

In [27]:
F1

tensor([0.9500, 0.3908])